const parts={
  scales:['01','Overlapping mirror scales','Individually reflective, shield-shaped pieces cover the faces. Most are reflective-only; selected positions are defined as light, photovoltaic or temperature cassettes beneath the same visible scale geometry.','Reflect the surrounding room while selected cassette positions admit light or carry a temperature probe.','How can each scale be retained, cleaned and replaced without sharp exposed edges or compromising an optical aperture?'],
  sensing:['02','Recessed optical sensing band','A continuous dark band interrupts the mirror skin. Separate apertures give sensors a view through a controlled window rather than through an arbitrary reflective coating.','Provide defined optical access and separate the sensor from decorative reflections.','Which wavelengths must pass, and how will reflections and the status light be baffled?'],
  seams:['03','Seams and scale overlap','Dark separation between pieces makes the layered shell legible. Overlap is part of the visual direction; the drawing does not specify a hinge or a moving mechanism.','Organize the skin into individual pieces with controlled edges and service access.','How much clearance is needed for assembly, thermal expansion and cleaning without trapping debris?'],
  base:['04','Inner chassis and central core','A darker internal structure sits behind the reflective skin and appears at the middle band. Its central chassis holds the controller, protected power board, wired interface and labeled surface connections.','Carry the main hardware, retain the outer shell and provide a defined service and mounting boundary.','Where will thermal paths, electrical isolation and any rated connector sit without compromising the exterior?'],
  window:['05','Hidden optical window','A selected scale can preserve the same outer silhouette while using a defined inset or a partly transmitting stack behind its reflective finish. This is the only credible route for a hidden light sensor or PV coupon.','Give one cassette a known optical path through the mirror skin.','Which stack keeps the desired appearance while providing measurable transmission at the required wavelengths?'],
  light:['06','Under-scale light cassette','A black light well and baffle sit behind a selected optical window, followed by a photodiode or ambient-light sensor and a labeled flex route to the core.','Measure light without confusing it with the status indicator or room reflections.','What is the finished-stack angular response, dark baseline and calibration range?'],
  pv:['07','Under-scale photovoltaic cassette','A separate selected scale can route transmitted light onto a small PV coupon with insulation, thermal backing and a dedicated conditioning input.','Turn part of the transmitted light into a measured electrical experiment.','What electrical output remains after the appearance, heat and available aperture tradeoffs are measured?'],
  carrier:['08','Carrier and service seam','The visible overlap is supported by a removable carrier behind the scales. It provides retention, labeled flex routing and a way to open the product without destroying the exterior.','Make the mirror skin buildable, inspectable and repairable.','Which datum, retainer and closure sequence maintains the seam quality across all six faces?'],
};
const favicon=document.createElement('link');
favicon.rel='icon';
favicon.type='image/svg+xml';
favicon.href='brand/favicon.svg';
document.head.append(favicon);
const portalMark=document.querySelector('.identity img');
if(portalMark)portalMark.src='brand/lattice-mark.svg';
function selectPart(button){
  const [number,title,description,role,question]=parts[button.dataset.part];
  document.getElementById('part-number').textContent=`SURFACE DETAIL / ${number}`;
  document.getElementById('part-title').textContent=title;
  document.getElementById('part-description').textContent=description;
  document.getElementById('part-role').textContent=role;
  document.getElementById('part-question').textContent=question;
  for(const other of document.querySelectorAll('[data-part]'))other.setAttribute('aria-pressed',String(other===button));
}
for(const button of document.querySelectorAll('[data-part]'))button.addEventListener('click',()=>selectPart(button));

const anatomyFigure=document.querySelector('.anatomy figure');
if(anatomyFigure){
  const additions=[['window','5','pin-5','Inspect 5: hidden optical window'],['light','6','pin-6','Inspect 6: under-scale light cassette'],['pv','7','pin-7','Inspect 7: under-scale photovoltaic cassette'],['carrier','8','pin-8','Inspect 8: carrier and service seam']];
  for(const [part,label,className,ariaLabel] of additions){
    const button=document.createElement('button');
    button.className=`anatomy-pin ${className}`;
    button.dataset.part=part;
    button.type='button';
    button.setAttribute('aria-label',ariaLabel);
    button.setAttribute('aria-pressed','false');
    button.textContent=label;
    button.addEventListener('click',()=>selectPart(button));
    anatomyFigure.append(button);
  }
}

const insideCube=document.querySelector('#inside-cube');
if(insideCube){
  insideCube.insertAdjacentHTML('afterend',`<section class="product-story solarskin-story" id="solarskin"><div class="story-heading"><span class="eyebrow">SOLARSKIN / LIGHT ENVIRONMENT</span><h2>A mirror can be functional.<br>But physics still decides.</h2><p>SolarSkin is not a claim that every mirrored scale harvests energy. It is a proposed family of selected scales that either reflect, admit light to a sensor, admit light to a PV coupon, or stay reflective-only. Every function needs its own measured optical and thermal path.</p></div><figure class="section-diagram"><img src="design/concepts/solarskin-stack.svg" width="1400" height="880" loading="lazy" alt="Detailed proposed SolarSkin stack showing protective layer, mirror finish or optical window, baffle, light or photovoltaic cassette, thermal interface, carrier and central core connection."><figcaption>Proposed stack · no coating, transmission, PV output or temperature performance has been selected or measured.</figcaption></figure><div class="solarskin-notes"><article><b>01 / Reflect</b><p>Most scales can stay mirror-only. Their job is appearance, not secretly collecting energy.</p></article><article><b>02 / Measure</b><p>A light cassette needs a window, baffle, calibration source and known angular response.</p></article><article><b>03 / Collect</b><p>A PV cassette needs its own electrical conditioning and a measured heat path.</p></article><article><b>04 / Explain</b><p>The core and Observatory must label which surface produced each reading and whether it is simulated or measured.</p></article></div><figure class="section-diagram light-environment"><img src="design/concepts/light-environment.svg" width="1400" height="760" loading="lazy" alt="Signal Cube environmental-light diagram separating direct source light, room reflections, light measurement, photovoltaic conditioning, internal status illumination and heat."><figcaption>Suggested M1 measurement environment · designed to expose the variables a manufacturer needs to control.</figcaption></figure><div class="hero-actions"><a class="action-link" href="optical/solarskin.md">Read the SolarSkin research brief ↗</a><a href="manufacturing/test-jigs/M1-DVP.md">See the optical and PV tests ↗</a></div></section>`);
}

const signalStory=document.querySelector('.signal-story');
if(signalStory){
  signalStory.insertAdjacentHTML('beforebegin',`<section class="product-story manufacturer-pilot" id="manufacturer-pilot"><div class="story-heading"><span class="eyebrow">NEXT PHASE / M1 PILOT</span><h2>Twelve cubes.<br>One real manufacturing question.</h2><p>Make the mirrored object repeatable before trying to make it massive. M1 is a proposed 12-unit engineering build: one common internal core, replaceable functional scales, three material variants and a fixture record for every cube.</p></div><div class="pilot-grid"><article><span>01</span><h3>Keep the core stable.</h3><p>The controller, protected power path, wired host interface and diagnostics stay common. A supplier can improve the shell or surface process without rebuilding the entire electrical system.</p></article><article><span>02</span><h3>Make the skin measurable.</h3><p>Four cubes each compare a concealed window, a semi-reflective stack and a split-function carrier. Light response, PV behavior, heat, glare and cosmetic quality become evidence.</p></article><article><span>03</span><h3>Test before closure.</h3><p>Each cassette and core passes a fixture check before the final face closes. The finished cube records identity, optical variant, test result and any rework in its as-built traveler.</p></article></div><div class="pilot-flow" aria-label="Proposed M1 engineering gates"><div><b>G0</b><small>CAD + risk review</small></div><div><b>G1</b><small>Optical coupons</small></div><div><b>G2</b><small>Core fixture</small></div><div><b>G3</b><small>First article</small></div><div><b>G4</b><small>12-unit evidence</small></div><div><b>G5</b><small>ME1 decision</small></div></div><div class="manufacturer-note"><div><span class="eyebrow">A MANUFACTURER GETS</span><p>A coherent challenge across finish development, precision mechanical assembly, flex/harness design, protected electronics, inspection and test automation—not an unbuildable render or an unbounded feature list.</p></div><div><span class="eyebrow">LATTICE GETS</span><p>A build process, cost structure, material evidence, test fixture and design-correction path that can become the basis for more modules in the physical computing fabric.</p></div></div><div class="hero-actions"><a class="action-link" href="manufacturing/M1-PILOT-PROGRAM.md">Read the M1 pilot program ↗</a><a href="manufacturing/suppliers/RFQ-SC-M1.md">Open the supplier response pack ↗</a><a href="manufacturing/test-jigs/M1-DVP.md">Inspect the M1 test plan ↗</a></div></section>`);
}

const pilotStory=document.querySelector('#manufacturer-pilot');
if(pilotStory){
  pilotStory.insertAdjacentHTML('afterend',`<section class="product-story project-blueprint" id="project-blueprint"><div class="story-heading"><span class="eyebrow">THE BUILD SYSTEM</span><h2>More than a cube.<br>A complete engineering trail.</h2><p>Every discipline needed to turn the Signal Cube into a reliable physical product has a home in the project. The pilot brings them together without pretending that documentation is hardware evidence.</p></div><div class="blueprint-grid"><a href="firmware/README.md"><b>Firmware</b><span>Safe boot, sampling, health and service</span></a><a href="hardware/README.md"><b>Hardware</b><span>Core, cassettes, power and harness rules</span></a><a href="protocols/README.md"><b>Protocols</b><span>Identity, messages, commands and transport</span></a><a href="calibration/README.md"><b>Calibration</b><span>Raw data, references and measurement limits</span></a><a href="quality/README.md"><b>Quality</b><span>Traceability, nonconformance and yield learning</span></a><a href="compliance/README.md"><b>Compliance</b><span>Claim boundaries and future review triggers</span></a><a href="simulator/README.md"><b>Simulator</b><span>Scenarios and model-versus-measurement rules</span></a><a href="observatory/README.md"><b>Observatory</b><span>How physical evidence becomes inspectable</span></a><a href="examples/README.md"><b>Examples</b><span>Three bounded, testable physical use cases</span></a><a href="operations/README.md"><b>Operations</b><span>Supervised pilot demonstrations and records</span></a></div><p class="hint">The M1 Pilot uses all ten areas. They are detailed design frameworks today; no folder claims a fabricated or qualified component.</p></section>`);
}

const blueprintStory=document.querySelector('#project-blueprint');
if(blueprintStory){
  blueprintStory.insertAdjacentHTML('afterend',`<section class="product-story newcomer-guide" id="start-here"><div class="story-heading"><span class="eyebrow">NEW HERE?</span><h2>Find the right way in.</h2><p>You can understand LATTICE without knowing every engineering term. Choose the route that matches why you are here.</p></div><div class="guide-grid"><a href="START_HERE.md"><b>I am exploring</b><span>What the Signal Cube is, what the software does today, and what remains a plan.</span><em>Start Here ↗</em></a><a href="docs/MANUFACTURER_ONBOARDING.md"><b>I make physical products</b><span>The first questions, pilot boundary, partner role and documents that matter before a quote.</span><em>Manufacturer onboarding ↗</em></a><a href="docs/GLOSSARY.md"><b>I need the language</b><span>Plain definitions for the core, cassettes, Twin, M1, DVP, DFM and maturity labels.</span><em>Read the glossary ↗</em></a></div></section>`);
}
